<?php

return [
    "items" => [
        "Hardware_Table",
        "Pro_Service_Table",
        "Quote_Table",
    ],
    "date_data" => [
        "Deal_Registration_Expiry",
        "Deal_Reg_Valid_To",
        "Valid_Till",
        "Payment_Date",
        "Quote_Valid_From",
        "Quote_Valid_To",
    ],
    "double_data" => [
        "list_price",
    ],
    "mapDealToZohoDeals" => [
        "status"=> "Stage",
        "approval_status"=> "Opportunity_Approval_Status",
        "sales_person"=> "Owner",
        "contact"=> "Contact_Name",
        "account"=> "Account_Name",
        "deal_name"=> "Deal_Name",
        "valid_from"=> "Deal_Registration_Expiry",
        "valid_to"=> "Deal_Reg_Valid_To",
        "vat"=> "VAT",
        "description"=> "Opportunity_Brief_Description",
        "notes"=> "Proposal_Quote_Notes",
        "customs"=> "Freight_and_Customs",
        "customs_value" => "Freight_and_Customs_Value",
    ],
    "mapDealToZohoQuotes" => [
        "customs"=> "Freight_and_Customs",
        "customs_value" => "Freight_and_Customs_Value",
        "status"=> "Quote_Status",
        "Total_Cost_Price"=> "Total_Cost_Price",
        "Total_Discount"=> "Total_Discount",
        "Total_Discount_Value"=> "Total_Discount_Value",
        "Total_Gross_Value"=> "Total_Gross_Value",
        "Total_Margin"=> "Total_Margin",
        "Total_Margin_Value"=> "Total_Margin_Value",
        "Total_Net_Value_Including_VAT"=> "Total_Net_Value_Including_VAT",
        "VAT_Value"=> "VAT_Value",
        "approval_status"=> "Approval_Status",
        "quote_stage"=> "Quote_Stage",
        "sales_person"=> "Owner",
        "contact"=> "Contact_Name",
        "account"=> "Account_Name",
        "subject"=> "Subject",
        "quote_no"=> "Quote_ID_No",
        "valid_from"=> "Quote_Valid_From",
        "valid_to"=> "Quote_Valid_To",
        "vat"=> "VAT",
        "description"=> "Description",
    ],
    "mapShippingToZohoDeals"=> [
        "contact"=> "Shipping_Contact_Name",
        "country"=> "Shipping_Country",
        "district"=> "Single_Line_18",
        "state"=> "Shipping_Province_State",
        "postal"=> "Shipping_ZIP_P_O_Box",
        "street"=> "Shipping_Street",
        "floor"=> "Shipping_Unit_Floor_No",
        "building"=> "Shipping_Building_Name",
    ],
    "mapShippingToZohoQuotes"=> [
        "contact"=> "Shipping_Contact_Name",
        "floor"=> "Shipping_Unit_Floor_No",
        "country"=> "Shipping_Country",
        "district"=> "Shipping_District",
        "state"=> "Shipping_State_City",
        "postal"=> "Shipping_ZIP_P_O_Box",
        "street"=> "Shipping_Street_Name",
        "building"=> "Shipping_Building_Name",
    ],
    "mapBillingToZohoDeals"=> [
        "contact"=> "Billing_Contact_Name",
        "country"=> "Billing_Country",
        "district"=> "Billing_District",
        "state"=> "Billing_Province_State",
        "postal"=> "Billing_ZIP_P_O_Box",
        "street"=> "Billing_Street",
        "floor"=> "Billing_Unit_Floor_No",
        "building"=> "Billing_Building_Name",
    ],
    "mapBillingToZohoQuotes"=> [
        "contact"=> "Billing_Contact_Name",
        "country"=> "Billing_Country",
        "district"=> "Billing_District",
        "state"=> "Billing_State_City",
        "postal"=> "Billing_ZIP_P_O_Box",
        "street"=> "Billing_Street_Name",
        "floor"=> "Billing_Unit_Floor_No",
        "building"=> "Billing_Building_Name",
    ],
    "mapPaymentTermsToZohoDeals"=> [
        "percent"=> "Payment",
        "value"=> "Payment_Value",
        "type"=> "Payment_Type",
        "method"=> "Payment_Method",
        "days"=> "Credit_Days",
        "end_date"=> "Payment_Date",
    ],
    "mapItemsToZohoDeals"=> [
        "product_id"=> "Product_Name",
        "vendor_part_number"=> "SKU_No",
        "type"=> "Product_Type",
        "description"=> "Product_Description",
        "quantity"=> "Quantity",
        "unit"=> "Unit",
        "cost_price"=> "Cost_Price",
        "unit_price"=> "Unit_Price",
        "margin_percent"=> "Margin",
        "margin"=> "Margin_Value",
        "discount"=> "Discount_Value",
        "discount_percent"=> "Discount",
        "gross"=> "Gross_Value",
        "net"=> "Net_Value",
    ],
    "mapItemsToZohoQuotes"=> [
        "product_id"=> "Product_Name",
        "description"=> "Description",
        "quantity"=> "Quantity",
        "cost_price"=> "Cost_Price",
        "unit_price"=> "List_Price",
        "discount"=> "Discount",
        "gross"=> "Total",
        "net"=> "Net_Total",
        "unit"=> "Unit",
        "tax"=> "Tax",
    ],
    "mapItemsToZohoQuotesProducts"=> [
        "product_id"=> "product",
        "quantity"=> "quantity",
        "discount"=> "Discount",
        "unit_price"=> "unit_price",
        "net"=> "net_total",
        "description"=> "product_description",
        "cost_price"=> "list_price",
        "gross"=> "total",
    ],
    "mapItemsToZohoProducts"=> [
        "name"=> "Product_Name",
        "description"=> "Product_Description",
        "type"=> "Product_Type",
        "unit_price"=> "Unit_Price",
        "cost_price"=> "Cost_Price",
        "margin"=> "margin_percentage",
        "part_number"=> "Product_Code",
    ],
    "mapGroupToCategory"=> [
        "Cloud" => "software",
        "Software" => "software",
        "Hardware" => "hardware",
        "Professional Service" => "service",
        "Implementation Service" => "service",
        "Consultancy" => "service",
        "Field Service" => "service",
        "Education and Training" => "service",
        "Annual Maintenance Contract" => "service",
        "Managed Service" => "service",
    ]
];
