import React, { useState, useEffect } from "react";
import Constants from "../../../helpers/samples";
import SelectFieldComponent from "./Fields/SelectFieldComponent";
import TextFieldComponent from "./Fields/TextFieldComponent";

export default function ({deal, pushDeal, pushQuote, pushAll, quote}) {
    return (
        <div className="container my-4">
            <div className="row">
                <div className="col-xl-2 col-lg-2 col-sm-2 col-8">
                    <TextFieldComponent type="text" label="Quote ID No." placeholder="Will be generated automatically" className="form-control" name="quote_no" disabled />
                </div>
                <div className="col-xl-1 col-lg-1 col-sm-1 col-2">
                    <label>&nbsp;</label>
                    <button disabled={!quote} onClick={pushQuote} type="button" className="btn btn-warning btn-sm btn-block">Push Quote</button>
                </div>
                <div className="col-xl-1 col-lg-1 col-sm-1 col-2 px-2">
                    <label>&nbsp;</label>
                    <button disabled={!quote} onClick={pushDeal} type="button" className="btn btn-primary btn-sm btn-block">Push Deal</button>
                </div>
                <div className="col-xl-2 col-lg-2 col-sm-2 col-9">
                    <SelectFieldComponent className="custom-select" label="Quote Status" name="status" disabled>
                        {
                            Constants.statusTypes.map(status => <option key={status.value} value={status.value}>{status.value}</option>)
                        }
                    </SelectFieldComponent>
                </div>
                <div className="col-xl-2 col-lg-2 col-sm-2 col-3">
                    <label>&nbsp;</label>
                    <button disabled={!quote} onClick={pushAll} type="button" className="btn btn-success btn-sm btn-block">Push All
                    </button>
                </div>
            </div>
            <div className="row mt-4">
                <div className="col-xl-2 col-lg-2 col-sm-2 col-3">
                    <div className="form-group">
                        <label>Generated By</label>
                        <input type="text" className="form-control" placeholder="Mohammed Al Janahi" value={deal?.Created_By?.name} disabled/>
                    </div>
                </div>
                <div className="col-xl-2 col-lg-2 col-sm-2 col-3">
                    <div className="form-group">
                        <label>Generated Date / Time</label>
                        <input type="text" className="form-control datetime-picker" value={deal?.Created_Time} disabled/>
                    </div>
                </div>
                <div className="col-xl-2 col-lg-2 col-sm-2 col-3">
                    <div className="form-group">
                        <label>Modified By</label>
                        <input type="text" className="form-control" placeholder="Mohammed Al Janahi" value={deal?.Modified_By?.name} disabled/>
                    </div>
                </div>
                <div className="col-xl-2 col-lg-2 col-sm-2 col-3">
                    <div className="form-group">
                        <label>Modified Date / Time</label>
                        <input type="text" className="form-control datetime-picker" placeholder="DD/MM/YYYY   11:59 PM" value={deal?.Modified_Time} disabled/>
                    </div>
                </div>
            </div>
            <hr />
        </div>
    )
}
